# Generated by Django 4.1.6 on 2023-02-13 02:13

import core.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_document_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage('/usr/local/var/cloud_vault/documents'), upload_to=core.models.file_location, validators=[core.models.validate_file_size]),
        ),
    ]
